# This is a config for E2B sandbox template.
# You can use template ID (gi5qjiq3gl49sgjyo03c) or template name (java) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("java") # Sync sandbox
# sandbox = await AsyncSandbox.create("java") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('java')

team_id = "cb9f72bb-1260-42c9-8890-96f693195cf5"
dockerfile = "e2b.Dockerfile"
template_name = "java"
template_id = "gi5qjiq3gl49sgjyo03c"
