# This is a config for E2B sandbox template.
# You can use template ID (b1ofzxcazrsil8g96nmh) or template name (js) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("js") # Sync sandbox
# sandbox = await AsyncSandbox.create("js") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('js')

team_id = "cb9f72bb-1260-42c9-8890-96f693195cf5"
dockerfile = "e2b.Dockerfile"
template_name = "js"
template_id = "b1ofzxcazrsil8g96nmh"
