# This is a config for E2B sandbox template.
# You can use template ID (4vpznq6iglpu1rmsnfy6) or template name (prime0-ng-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("prime0-ng-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("prime0-ng-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('prime0-ng-test')

team_id = "cb9f72bb-1260-42c9-8890-96f693195cf5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "prime0-ng-test"
template_id = "4vpznq6iglpu1rmsnfy6"
